# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facial_recognition.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'facial_recognition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66\x61\x63ial_recognition.proto\x12\x12\x66\x61\x63ial_recognition\"2\n\x10SaveImageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"H\n\x11SaveImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tlandmarks\x18\x03 \x03(\x05\"!\n\x10GetUserIdRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"F\n\x11GetUserIdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x32\xce\x01\n\x18\x46\x61\x63ialRecognitionService\x12X\n\tSaveImage\x12$.facial_recognition.SaveImageRequest\x1a%.facial_recognition.SaveImageResponse\x12X\n\tGetUserId\x12$.facial_recognition.GetUserIdRequest\x1a%.facial_recognition.GetUserIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facial_recognition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEIMAGEREQUEST']._serialized_start=48
  _globals['_SAVEIMAGEREQUEST']._serialized_end=98
  _globals['_SAVEIMAGERESPONSE']._serialized_start=100
  _globals['_SAVEIMAGERESPONSE']._serialized_end=172
  _globals['_GETUSERIDREQUEST']._serialized_start=174
  _globals['_GETUSERIDREQUEST']._serialized_end=207
  _globals['_GETUSERIDRESPONSE']._serialized_start=209
  _globals['_GETUSERIDRESPONSE']._serialized_end=279
  _globals['_FACIALRECOGNITIONSERVICE']._serialized_start=282
  _globals['_FACIALRECOGNITIONSERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
